name: Cria√ß√£o de user stories
run-name: Running - Cria√ß√£o user stories

on:
  workflow_call: {}

permissions:
  contents: write
  pull-requests: write
  
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
    
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: pj-integration-agent/automation
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }} 
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          pip install groq pytest pytest-bdd
 
      - name: Generate User Stories from criterios.md
        run: python ai/generate/generate_user_stories.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      # - name: Generate Tests from BDD
      #   run: python ai/generate/generate_tests_from_bdd.py
      #   env:
      #     GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Commit user stories
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin ${{ github.ref_name }}
          git add .
          git commit -m "ü§ñ Gerando user stories" || echo "Nada para commitar"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
